name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test and create coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Get dependencies and verify
        run: |
          go mod download
          go mod verify

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
